server:
  port: 8014

spring:
  application:
    name: nacos-provider-meeting
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.110.112:8848
        #server-addr: localhost:8848
  datasource:
    druid:
      username: root
      password: My-Linux-Mysql123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.24.57.96:3306/aigov?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      #password: 314159265
      #url: jdbc:mysql://localhost:3306/mydatisdb?serverTimezone=GMT%2B8
# 准备采用基于注解的mybatis mapper